# ✅ NumPy Operations on Green AI Dataset
This notebook demonstrates all major NumPy operations using a simple dataset of solar and wind energy usage across five cities in India.

In [1]:
import numpy as np

# Dataset: Green energy usage in MW
cities = np.array(['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai'])
solar_energy = np.array([120, 150, 180, 90, 130])
wind_energy = np.array([100, 130, 160, 80, 110])
solar_energy

array([120, 150, 180,  90, 130])

## 1. Array Creation

In [2]:
a = np.array([1, 2, 3])
b = np.zeros(3)
c = np.ones((2, 2))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)
f = np.random.rand(10)

print("Array a:", a)
print("Zeros b:", b)
print("Ones c:\n", c)
print("Arange d:", d)
print("Linspace e:", e)
print("Random f:", f)

Array a: [1 2 3]
Zeros b: [0. 0. 0.]
Ones c:
 [[1. 1.]
 [1. 1.]]
Arange d: [0 2 4 6 8]
Linspace e: [0.   0.25 0.5  0.75 1.  ]
Random f: [0.18450165 0.29616133 0.28038385 0.11498914 0.28747856 0.48185134
 0.41091372 0.16883658 0.57642009 0.86845618]


## 2. Array Attributes

In [3]:
print("Shape:", solar_energy.shape)
print("Datatype:", solar_energy.dtype)
print("Dimensions:", solar_energy.ndim)

Shape: (5,)
Datatype: int64
Dimensions: 1


## 3. Indexing and Slicing

In [4]:
print("First city:", cities[0])
print("First 3 solar energy values:", solar_energy[:3])

First city: Delhi
First 3 solar energy values: [120 150 180]


## 4. Arithmetic Operations

In [ ]:
total_energy = solar_energy + wind_energy
diff_energy = solar_energy - wind_energy
energy_squared = solar_energy ** 2

print("Total energy:", total_energy)
print("Difference in energy:", diff_energy)
print("Squared solar energy:", energy_squared)

Total energy: [220 280 340 170 240]
Difference in energy: [20 20 20 10 20]
Squared solar energy: [14400 22500 32400  8100 16900]


## 5. Statistical Operations

In [6]:
print("Mean (solar):", np.mean(solar_energy))
print("Median (wind):", np.median(wind_energy))
print("Standard Deviation (total):", np.std(total_energy))
print("Variance (total):", np.var(total_energy))
print("Minimum (solar):", np.min(solar_energy))
print("Maximum (solar):", np.max(solar_energy))

Mean (solar): 134.0
Median (wind): 110.0
Standard Deviation (total): 57.271284253105414
Variance (total): 3280.0
Minimum (solar): 90
Maximum (solar): 180


## 6. Reshape and Transpose

In [7]:
energy_matrix = np.array([solar_energy, wind_energy])
print("Original Matrix:\n", energy_matrix)
print("Transposed Matrix:\n", energy_matrix.T)

Original Matrix:
 [[120 150 180  90 130]
 [100 130 160  80 110]]
Transposed Matrix:
 [[120 100]
 [150 130]
 [180 160]
 [ 90  80]
 [130 110]]


## 7. Boolean Indexing

In [8]:
print("Cities with solar > 120:", cities[solar_energy > 120])

Cities with solar > 120: ['Mumbai' 'Bangalore' 'Chennai']


## 8. Aggregation Functions

In [9]:
print("Total solar energy:", np.sum(solar_energy))
print("Product of wind energy:", np.prod(wind_energy))
print("Cumulative sum (solar):", np.cumsum(solar_energy))

Total solar energy: 670
Product of wind energy: 18304000000
Cumulative sum (solar): [120 270 450 540 670]


## 9. Mathematical Functions

In [10]:
print("Square root (solar):", np.sqrt(solar_energy))
print("Exponential (wind):", np.exp(wind_energy // 100))
print("Natural log (solar):", np.log(solar_energy))
print("Absolute difference:", np.abs(solar_energy - wind_energy))

Square root (solar): [10.95445115 12.24744871 13.41640786  9.48683298 11.40175425]
Exponential (wind): [2.71828183 2.71828183 2.71828183 1.         2.71828183]
Natural log (solar): [4.78749174 5.01063529 5.19295685 4.49980967 4.86753445]
Absolute difference: [20 20 20 10 20]


## 10. Sorting and Searching

In [11]:
print("Sorted total energy:", np.sort(total_energy))
print("Index of max solar:", np.argmax(solar_energy))
print("Index of min wind:", np.argmin(wind_energy))

Sorted total energy: [170 220 240 280 340]
Index of max solar: 2
Index of min wind: 3


## 11. Broadcasting

In [12]:
increased_solar = solar_energy * 1.1
print("Solar energy increased by 10%:", increased_solar)

Solar energy increased by 10%: [132. 165. 198.  99. 143.]


## 12. Stacking Arrays

In [13]:
v_stack = np.vstack((solar_energy, wind_energy))
h_stack = np.hstack((solar_energy, wind_energy))
print("Vertical stack:\n", v_stack)
print("Horizontal stack:\n", h_stack)

Vertical stack:
 [[120 150 180  90 130]
 [100 130 160  80 110]]
Horizontal stack:
 [120 150 180  90 130 100 130 160  80 110]


## 13. Copying and Memory

In [14]:
copy_solar = solar_energy.copy()
ref_solar = solar_energy

copy_solar[0] = 999
ref_solar[1] = 888

print("Original solar:", solar_energy)
print("Copied solar (deep):", copy_solar)
print("Reference solar (shallow):", ref_solar)

Original solar: [120 888 180  90 130]
Copied solar (deep): [999 150 180  90 130]
Reference solar (shallow): [120 888 180  90 130]


## 14. Set Operations

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Union:", np.union1d(a, b))
print("Intersection:", np.intersect1d(a, b))
print("Difference a - b:", np.setdiff1d(a, b))

Union: [1 2 3 4 5 6]
Intersection: [3 4]
Difference a - b: [1 2]


In [23]:
w1=np.arange(12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4)

In [17]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [26]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])